FROM r-base:latest

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

MAINTAINER Zan Yuan <seqyuan@gmail.com>

RUN Rscript -e "install.packages(c('remotes', 'ggplot2', 'Seurat'))"
RUN Rscript -e "remotes::install_github('sunduanchen/Scissor', upgrade='never')"
RUN Rscript -e "remotes::install_github('YuLab-SMU/clusterProfiler', upgrade='never')"

