FROM docker

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

RUN apk add --no-cache bash bash-doc bash-completion
RUN apk add 'R>3.6.0-suffix'
#RUN apk add --no-cache R-dev

RUN if [ -e /bin/sh ];then rm /bin/sh ; fi && \
	if [ -e /bin/bash ];then ln -s /bin/bash /bin/sh ; fi

#RUN R -e "install.packages('gapminder', repos = 'http://cran.us.r-project.org')"
#RUN R -e "install.packages('BiocManager', repos = 'http://cran.us.r-project.org'))"
#RUN R -e "install.packages('devtools', repos='http://cran.us.r-project.org')"
#RUN R -e "install.packages('BiocManager', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('BiocManager', repos='http://mirror.bjtu.edu.cn/cran/')"

RUN R -e "install.packages('devtools', repos='https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"

#RUN R -e "devtools::install_github('dynverse/dyno')"


WORKDIR /app
CMD R --version
